//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public License()
        {
            this.ActivatedLicenses = new HashSet<ActivatedLicens>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TerminationTime { get; set; }
        public int LicenseTypeID { get; set; }
        public string LicenseCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivatedLicens> ActivatedLicenses { get; set; }
        public virtual LicenseType LicenseType { get; set; }

        public bool Rewrite(License from)
        {
            if(from == null)
            {
                return false;
            }

            this.TerminationTime = from.TerminationTime;
            this.LicenseTypeID = from.LicenseTypeID;
            this.LicenseCode = from.LicenseCode;

            return true;
        }
    }
}
